# Generated by Django 2.1.1 on 2018-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('ph_no', models.IntegerField()),
            ],
        ),
    ]
