# Generated by Django 2.1.1 on 2018-10-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(default='MALE', max_length=30),
            preserve_default=False,
        ),
    ]
