# Generated by Django 2.1.1 on 2018-10-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_users_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=40)),
                ('reciever', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wallpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=110)),
            ],
        ),
    ]
