# Generated by Django 2.1.1 on 2018-10-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_friends_wallpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='frequests',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=40)),
                ('reciever', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='friends',
        ),
    ]
