# Generated by Django 2.1.1 on 2019-01-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20181230_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/%y%m%d')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='users',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
